description: mmp 210 class website
class: MMP 210
semester: 22f
semester_string: fall
schedule: false
# baseurl: /
layouts_dir: slides/_jeks/layouts
includes_dir: slides/_jeks/includes
# Exclude these files from your production _site
exclude:
  - README.md
  - update.sh
  - screen_casts/